# Generated by Django 5.0.7 on 2024-07-28 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_domotica_unidades_computadora_licencia_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Computadora',
            new_name='Tienda',
        ),
        migrations.RemoveField(
            model_name='licencia',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='periferico',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Domotica',
        ),
        migrations.DeleteModel(
            name='Licencia',
        ),
        migrations.DeleteModel(
            name='Periferico',
        ),
    ]
